resources:
- repo: self
name: $(date:yyyy).1.0$(rev:.rrr)
queue:
  name: Hosted Linux Preview
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'Run unit tests'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test:unit'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  displayName: 'Copy dist to artifacts'
  inputs:
    SourceFolder: dist
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy ARM Templates to artifacts'
  inputs:
    SourceFolder: deploy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish website content'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: web

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM templates'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)/deploy'
    ArtifactName: arm